### PR TITLE
Added background Color change functionality

### PR DESCRIPTION
**Pull request by Arsh-78**
Added the Change bacground functionality via following changes

- Added the ColorPicker Dependency for Color wheel
- Modified the main activity layout to contain both the canvas and a button to change the background color
- demo :
(Note due to some software glitch the wheel appears distorted in gif but is actually working finr attached a screenshot for correspondence)

gif:
ChangeBgColor

wheel actual view : 
one

### CODE REVIEW

**Comment by anshulhq** [comment]
Hey, I'm getting merge conflicts in all 3 files, Can you check it once ? I'm unable to resolve on my own.

**Comment by Arsh-78** [comment]
> Hey, I'm getting merge conflicts in all 3 files, Can you check it once ? I'm unable to resolve on my own.

@anshul-kr1 can you please try now

**Comment by Arsh-78** [comment]
Bro I have resolved the conflicts can you please check

**Comment by Arsh-78** [comment]
can you please confirm the status @anshul-kr1

**Comment by anshulhq** [comment]
@Arsh-78 Well done. Your PR is merged. Thanks for contributing!

**Pull request merged**
